import os
import sys
import json
from pathlib import Path

try:
    import tree_sitter
    import tree_sitter_python
    from tree_sitter import Language, Parser, Query
except ImportError:
    print("Warning: tree-sitter or tree-sitter-python not installed. Run `pip install tree-sitter tree-sitter-python`")
    sys.exit(1)

def build_ast_map(directory):
    # Initialize Tree-sitter
    PY_LANGUAGE = Language(tree_sitter_python.language())
    parser = Parser(PY_LANGUAGE)
    
    # Query to extract class and function signatures
    query_str = """
    (class_definition name: (identifier) @class_name)
    (function_definition name: (identifier) @func_name)
    """
    query = Query(PY_LANGUAGE, query_str)
    
    ignore_dirs = {'.git', 'node_modules', 'venv', '.venv', '__pycache__', '.opencode', 'dist'}
    
    output = []
    output.append("# Project Map (AST RAG Index)\n")
    output.append("*Autogenerated codebase map for AI agent context optimization*\n")
    
    for root, dirs, files in os.walk(directory):
        # Filter directories
        dirs[:] = [d for d in dirs if d not in ignore_dirs]
        
        # Calculate depth for tree formatting
        level = root.replace(directory, '').count(os.sep)
        indent = '│   ' * (level)
        folder = os.path.basename(root)
        if folder:
            output.append(f"{indent}├── {folder}/")
            
        sub_indent = '│   ' * (level + 1)
        
        for file in files:
            if not file.endswith('.py'):
                # We just list the file if it's not python, or ignore it if we only want py files.
                # Let's list only code files
                if file.endswith(('.ts', '.js', '.json', '.md', '.yml', '.yaml')):
                    output.append(f"{sub_indent}├── {file}")
                continue
                
            file_path = os.path.join(root, file)
            output.append(f"{sub_indent}├── {file}")
            
            try:
                with open(file_path, 'rb') as f:
                    code_bytes = f.read()
                    
                tree = parser.parse(code_bytes)
                func_sigs = []
                class_names = []
                if hasattr(query, 'captures'):
                    captures = query.captures(tree.root_node)
                    for capture in captures:
                        node = capture[0]
                        tag = capture[1]
                        text = code_bytes[node.start_byte:node.end_byte].decode('utf-8')
                        if tag == 'class_name':
                            class_names.append(text)
                        elif tag == 'func_name':
                            func_sigs.append(text)
                else:
                    cursor = tree_sitter.QueryCursor(query)
                    captures = cursor.captures(tree.root_node)
                    all_nodes = []
                    for tag, nodes in captures.items():
                        for node in nodes:
                            all_nodes.append((tag, node))
                    
                    # Sort nodes by start_byte to preserve file order
                    all_nodes.sort(key=lambda x: x[1].start_byte)
                    
                    for tag, node in all_nodes:
                        text = code_bytes[node.start_byte:node.end_byte].decode('utf-8')
                        if tag == 'class_name':
                            class_names.append(text)
                        elif tag == 'func_name':
                            func_sigs.append(text)
                
                for cls in class_names:
                    output.append(f"{sub_indent}│   # class {cls}(...)")
                for func in func_sigs:
                    output.append(f"{sub_indent}│   # def {func}(...)")
            except Exception as e:
                output.append(f"{sub_indent}│   # Error parsing AST: {str(e)}")
                
    return "\n".join(output)

if __name__ == '__main__':
    target_dir = os.getcwd()
    if len(sys.argv) > 1:
        target_dir = os.path.abspath(sys.argv[1])
        
    project_map = build_ast_map(target_dir)
    out_path = os.path.join(target_dir, 'project_map.md')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(project_map)
    print(f"Generated project_map.md at {out_path}")
